on:
    push:
      branches:
        - main 

    pull_request:
      branches:
        - main 

jobs:
    build-and-test-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                toolchain: stable
                components: rustfmt, clippy

            - name: Run cargo test
              run: cargo test --all-features

            - name: Run cargo build
              run: cargo build --all

            - name: Run cargo fmt
              run: cargo fmt --all -- --check

            - name: Run cargo clippy
              run: cargo clippy --all -- -D warnings

            - name: Build release
              run: cargo build --release
